name: hlcv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - tissue-forge
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - matplotlib
  - pandas
  - numpy
  - wandb
  - accelerate
  - deepspeed
  - pip
  - gcc_linux-64
  - gxx_linux-64
  - tissue-forge
  - libglib
  - pip:
    - gdown
    - -r requirements.txt
