name: hlcv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - tissue-forge
dependencies:
  -  mkl==2024.0 
  - torchvision=0.14.1=py38_cu116
  - pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - setuptools=69.5.1
  - pip
  - pip:
    - gdown
    - -r requirements.txt
    - ./stable-dreamfusion/raymarching
    - ./stable-dreamfusion/freqencoder
    - ./stable-dreamfusion/gridencoder
    - ./stable-dreamfusion/shencoder