name: hlcv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - matplotlib
  - pandas
  - numpy
  - notebook
  - transformers
  - scikit-learn
  - jupyter
  - datasets
  - diffusers
  - wandb
  - accelerate
  - deepspeed
  - pip:
    - evaluate
    - rouge_score
    - trl
    - mpi4py